/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.frames.commissioner;

import Modelo.Commissioner;

/**
 *
 * @author Francisco Miguel Carrasquilla Rodríguez-Córdoba
 * <afcarrasquilla@iesfranciscodelosrios.es>
 */
public class CommissionerDetailsPanel extends javax.swing.JPanel {

    private Commissioner commissioner;
    
    private boolean edit;
    
    public CommissionerDetailsPanel() {
        initComponents();
    }

    public Commissioner getCommissioner() {
        return commissioner;
    }

    public void setCommissioner(Commissioner commissioner) {
        this.commissioner = commissioner;
    }

    public boolean isEdit() {
        return edit;
    }

    public void setEdit(boolean edit) {
        this.edit = edit;
        TextDNI.setEditable(edit);
        TextName.setEditable(edit);
    }
    
    public void loadData(){
        if (commissioner != null){
            TextDNI.setText(commissioner.getDni());
            TextName.setText(commissioner.getName());
        }else{
            TextDNI.setText("");
            TextName.setText("");
        }
        TextDNI.requestFocus();
    }
    
    public void saveData(){
        if (commissioner == null) {
            commissioner = new Commissioner();
        }
        commissioner.setDni(TextDNI.getText());
        commissioner.setName(TextName.getText());
    }
    
    public boolean checkData(){
        boolean noEmpty = false;
        if (!TextDNI.getText().equals("") && !TextName.getText().equals("")) {
            noEmpty = true;
        }
        return noEmpty;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DNI = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        TextDNI = new javax.swing.JTextField();
        TextName = new javax.swing.JTextField();

        DNI.setText("DNI:");

        Name.setText("Nombre:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(DNI)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Name)
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TextName)
                    .addComponent(TextDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DNI)
                    .addComponent(TextDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name)
                    .addComponent(TextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(238, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DNI;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField TextDNI;
    private javax.swing.JTextField TextName;
    // End of variables declaration//GEN-END:variables
}

