/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.frames.multisportcenter;


import Modelo.DAO.SportComplexDAO;
import Modelo.MultiSportCenter;
import Modelo.SportComplex;
import Modelo.auxiliary.DAOException;
import Vista.frames.sportcenter.SportComplexComboModel;
import Vista.frames.sportcenter.SportComplexComboView;

/**
 *
 * @author Francisco Miguel Carrasquilla Rodríguez-Córdoba
 * <afcarrasquilla@iesfranciscodelosrios.es>
 */
public class MultiSportCenterDetailsPanel extends javax.swing.JPanel {

    private MultiSportCenter multiSportCenter;
    
    private boolean edit;
    
    private SportComplexComboModel comboModel;
    
    public MultiSportCenterDetailsPanel() {
        initComponents();
        comboModel = new SportComplexComboModel(null);
    }
    
    public MultiSportCenterDetailsPanel(SportComplexDAO dao) throws DAOException {
        initComponents();
        comboModel = new SportComplexComboModel(dao);
        comboModel.update();
        ComboBoxSportComplex.setModel(comboModel);
    }

    public MultiSportCenter getMultiSportCenter() {
        return multiSportCenter;
    }

    public void setMultiSportCenter(MultiSportCenter multiSportCenter) {
        this.multiSportCenter = multiSportCenter;
    }

    public boolean isEdit() {
        return edit;
    }

    public void setEdit(boolean edit) {
        this.edit = edit;
        ComboBoxSportComplex.setEnabled(edit);
        TextInformation.setEditable(edit);
    }

    public SportComplexComboModel getComboModel() {
        return comboModel;
    }

    public void setComboModel(SportComplexComboModel comboModel) throws DAOException {
        this.comboModel = comboModel;
        ComboBoxSportComplex.setModel(comboModel);
        comboModel.update();
    }
    
    public void loadData(){
        if (multiSportCenter != null) {
            SelectItemComboBox();
            TextInformation.setText(multiSportCenter.getInformation());
        }else{
            TextInformation.setText("");
        }
        TextInformation.requestFocus();
    }
    
    public void SelectItemComboBox() {
        boolean encontrado=false;
        for (int i = 0; i < ComboBoxSportComplex.getItemCount() && !encontrado; i++) {
            if (ComboBoxSportComplex.getItemAt(i).getId() == 
                    multiSportCenter.getId()) {
                ComboBoxSportComplex.setSelectedIndex(i);
                encontrado=true;
            }
        }
    }
    
    public void saveData(){
        if (multiSportCenter == null) {
            multiSportCenter = new MultiSportCenter();
        }
        multiSportCenter.setInformation(TextInformation.getText());
        SportComplexComboView sccv =
                (SportComplexComboView) ComboBoxSportComplex.getSelectedItem();
        SportComplex sportComplex = (SportComplex) sccv;
        multiSportCenter.setId(sportComplex.getId());
        multiSportCenter.setLocation(sportComplex.getLocation());
        multiSportCenter.setBoss(sportComplex.getBoss());
    }
    
    public boolean checkData(){
        boolean noEmpty = false;
        if (!TextInformation.getText().equals("")) {
            noEmpty = true;
        }
        return noEmpty;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Id = new javax.swing.JLabel();
        Information = new javax.swing.JLabel();
        ComboBoxSportComplex = new javax.swing.JComboBox<>();
        TextInformation = new javax.swing.JTextField();

        Id.setText("Id:");

        Information.setText("Información:");

        ComboBoxSportComplex.setModel(new javax.swing.DefaultComboBoxModel<>(new SportComplexComboView[] { }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Information)
                    .addComponent(Id))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextInformation)
                    .addComponent(ComboBoxSportComplex, 0, 280, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Id)
                    .addComponent(ComboBoxSportComplex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Information)
                    .addComponent(TextInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(238, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<SportComplexComboView> ComboBoxSportComplex;
    private javax.swing.JLabel Id;
    private javax.swing.JLabel Information;
    private javax.swing.JTextField TextInformation;
    // End of variables declaration//GEN-END:variables
}

