/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.frames.sportcomplex;

import Modelo.DAO.HeadquarterDAO;
import Modelo.Headquarter;
import Modelo.SportComplex;
import Modelo.auxiliary.DAOException;

/**
 *
 * @author Francisco Miguel Carrasquilla Rodríguez-Córdoba
 * <afcarrasquilla@iesfranciscodelosrios.es>
 */
public class SportComplexDetailsPanel extends javax.swing.JPanel {

    private SportComplex sportComplex;
    
    private boolean edit;
    
    private HeadquarterComboModel comboModel;
    
    public SportComplexDetailsPanel() {
        initComponents();
        comboModel = new HeadquarterComboModel(null);
    }
    
    public SportComplexDetailsPanel(HeadquarterDAO dao) throws DAOException {
        initComponents();
        comboModel = new HeadquarterComboModel(dao);
        comboModel.update();
        ComboBoxHeadquarter.setModel(comboModel);    
    }
    
     /**
     * @return the sportComplex
     */
    public SportComplex getSportComplex() {
        return sportComplex;
    }

    /**
     * @param sportComplex the sportComplex to set
     */
    public void setSportComplex(SportComplex sportComplex) {
        this.sportComplex = sportComplex;
    }

    /**
     * @return the edit
     */
    public boolean isEdit() {
        return edit;
    }

    /**
     * @param edit the edit to set
     */
    public void setEdit(boolean edit) {
        this.edit = edit;
        TextLocation.setEditable(edit);
        TextBoss.setEditable(edit);
        ComboBoxHeadquarter.setEnabled(edit);
    }

    public HeadquarterComboModel getComboModel() {
        return comboModel;
    }

    public void setComboModel(HeadquarterComboModel comboModel) throws DAOException {
        this.comboModel = comboModel;
        ComboBoxHeadquarter.setModel(comboModel);
        comboModel.update();
    }
    
    public void loadData(){
        if (sportComplex != null){
            TextLocation.setText(sportComplex.getLocation());
            TextBoss.setText(sportComplex.getBoss());
            SelectItemComboBox();
        }else{
            TextLocation.setText("");
            TextBoss.setText("");
        }
        TextLocation.requestFocus();
    }

    public void SelectItemComboBox() {
        boolean encontrado=false;
        for (int i = 0; i < ComboBoxHeadquarter.getItemCount() && !encontrado; i++) {
            if (ComboBoxHeadquarter.getItemAt(i).getId() == 
                    sportComplex.getHeadquarter().getId()) {
                ComboBoxHeadquarter.setSelectedIndex(i);
                encontrado=true;
            }
        }
    }
    
    public void saveData(){
        if (sportComplex == null){
            sportComplex = new SportComplex();
        }
        sportComplex.setLocation(TextLocation.getText());
        sportComplex.setBoss(TextBoss.getText());
        HeadquarterComboView hcv = 
                (HeadquarterComboView) ComboBoxHeadquarter.getSelectedItem();
        Headquarter headquarter = (Headquarter) hcv;
        sportComplex.setHeadquarter(headquarter);
    }
    
    public boolean checkData(){
        boolean noEmpty = false;
        if (!TextBoss.getText().equals("") && !TextLocation.getText().equals("")) {
            noEmpty = true;
        }
        return noEmpty;
    }

    /**
     * This method is called from within the constructor to initialize
     * the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Location = new javax.swing.JLabel();
        TextLocation = new javax.swing.JTextField();
        Boss = new javax.swing.JLabel();
        TextBoss = new javax.swing.JTextField();
        Headquarter = new javax.swing.JLabel();
        ComboBoxHeadquarter = new javax.swing.JComboBox<>();

        Location.setText("Localizacion:");

        Boss.setText("Jefe:");

        TextBoss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBossActionPerformed(evt);
            }
        });

        Headquarter.setText("Sede:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Location)
                    .addComponent(Boss)
                    .addComponent(Headquarter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextBoss, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(TextLocation)
                    .addComponent(ComboBoxHeadquarter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Location)
                    .addComponent(TextLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boss)
                    .addComponent(TextBoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Headquarter)
                    .addComponent(ComboBoxHeadquarter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(207, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextBossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextBossActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextBossActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Boss;
    private javax.swing.JComboBox<HeadquarterComboView> ComboBoxHeadquarter;
    private javax.swing.JLabel Headquarter;
    private javax.swing.JLabel Location;
    private javax.swing.JTextField TextBoss;
    private javax.swing.JTextField TextLocation;
    // End of variables declaration//GEN-END:variables

}

